<?php

return [
    // General
    'loading'            => 'Loading...',
    'search'             => 'Search',
    'search_placeholder' => 'Search products...',
    'no_results'         => 'No results found',
    'view_all'           => 'View All',
    'read_more'          => 'Read More',
    'close'              => 'Close',
    'save'               => 'Save',
    'cancel'             => 'Cancel',
    'submit'             => 'Submit',
    'sort_by'            => 'Sort by',
    'filter'             => 'Filter',
    'clear_filters'      => 'Clear Filters',

    // Navigation
    'home'     => 'Home',
    'shop'     => 'Shop',
    'blog'     => 'Blog',
    'contact'  => 'Contact',
    'about'    => 'About',
    'account'  => 'Account',
    'logout'   => 'Logout',

    // Product
    'add_to_cart'       => 'Add to Cart',
    'buy_now'           => 'Buy Now',
    'preorder_now'      => 'Pre-order Now',
    'out_of_stock'      => 'Out of Stock',
    'in_stock'          => 'In Stock',
    'quantity'          => 'Quantity',
    'sku'               => 'SKU',
    'brand'             => 'Brand',
    'category'          => 'Category',
    'description'       => 'Description',
    'specifications'    => 'Specifications',
    'reviews'           => 'Reviews',
    'write_review'      => 'Write a Review',
    'no_reviews'        => 'No reviews yet',
    'related_products'  => 'Related Products',
    'shipping_included' => 'Shipping Included',
    'free_shipping'     => 'Free Shipping',
    'warranty'          => 'Warranty',
    'return_policy'     => 'Return Policy',
    'share'             => 'Share',
    'wishlist_add'      => 'Add to Wishlist',
    'viewing_now'       => '{count} people are viewing this item right now',
    'choose_variant'    => 'Choose {attribute}',
    'select_option'     => 'Select an option',

    // Sort options
    'sort_newest'     => 'Newest',
    'sort_price_asc'  => 'Price: Low to High',
    'sort_price_desc' => 'Price: High to Low',
    'sort_featured'   => 'Featured',

    // Cart
    'cart'              => 'Cart',
    'cart_empty'        => 'Your cart is empty',
    'continue_shopping' => 'Continue Shopping',
    'checkout'          => 'Checkout',
    'subtotal'          => 'Subtotal',
    'total'             => 'Total',
    'shipping'          => 'Shipping',
    'discount'          => 'Discount',
    'coupon_code'       => 'Coupon Code',
    'apply'             => 'Apply',
    'remove'            => 'Remove',
    'items_count'       => '{count} items',

    // Checkout
    'place_order'     => 'Place Order',
    'full_name'       => 'Full Name',
    'phone'           => 'Phone',
    'email'           => 'Email',
    'address'         => 'Address',
    'city'            => 'City',
    'payment_method'  => 'Payment Method',
    'cash_on_delivery' => 'Cash on Delivery',
    'order_notes'     => 'Order Notes (optional)',
    'processing'      => 'Processing...',

    // Account
    'login'            => 'Login',
    'register'         => 'Register',
    'my_orders'        => 'My Orders',
    'my_account'       => 'My Account',
    'profile'          => 'Profile',
    'password'         => 'Password',
    'forgot_password'  => 'Forgot Password',
    'send_otp'         => 'Send OTP',
    'verify_otp'       => 'Verify OTP',
    'otp_sent'         => 'OTP sent to your phone',

    // Order
    'order_id'          => 'Order ID',
    'order_date'        => 'Order Date',
    'order_status'      => 'Order Status',
    'track_order'       => 'Track Order',
    'order_confirmed'   => 'Order Confirmed',
    'thank_you'         => 'Thank you for your order!',

    // Misc
    'showing_results'  => 'Showing {from}-{to} of {total} results',
    'price'            => 'Price',
    'off'              => 'off',
    'new'              => 'New',
    'featured'         => 'Featured',
    'sale'             => 'Sale',
    'sold_out'         => 'Sold Out',
];
